### ISSUE TITLE
Unable to sync contacts

### ISSUE THREAD

**Issue by jamie-dit** [lennmedia/crisp-whmcs#1]
Hey there,

When attempting the initial sync, this error message appears:

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname_db.mod_crisp' doesn't exist in /home/user/domains/whmcs.domain/public_html/vendor/illuminate/database/Connection.php:458
Stack trace:
#0 /home/user/domains/whmcs.domain/public_html/vendor/illuminate/database/Connection.php(458): PDO->prepare('insert into `mo...')
```

**Comment by lennarttd** [comment]
Hi Jamie. The table should be created/dropped on activation/deactivation of the WHMCS Addon.
Could you please try to disable and enable the addon to see if the error persists?

Which version of WHMCS are you running?

**Comment by jamie-dit** [comment]
Hey there. I'm using the latest version of WHMCS. Got it working by deactivating and reactivating.
