### ISSUE TITLE
SYNC Timeout

### ISSUE THREAD

**Issue by MrFreezia** [lennmedia/crisp-whmcs#3]
Our SYNC keep's timing out. We have 20K customers registered on WHMCS. We had to disable Cloud Flare as it has a timeout of 100 seconds, is there any error log to confirm is things are being synced? or a work-around?

**Comment by lennarttd** [comment]
Hi,

First of all, thank you for using our Crisp WHMCS PRO plugin.

When performing a sync, the plugin will put all client IDs into a queue in the database. This database column is called 'mod_crisp'. Can you confirm this table is populated?

If so, whenever the WHMCS cron runs, it will sync several clients. As the WHMCS cron is recommended to run every 5 minutes, this table should empty itself after some time.

Please note that on large installations the initial sync can take up to several days and the initial sync is only needed once (or in case of a big plugin update). Once everything is synced, all data will automatically stay in sync while using the plugin.

**Comment by MrFreezia** [comment]
Thank you for your reply and for your time on the LIVECHAT -- truly a HERO.

So our findings figured out it's timing out due to the Connection Limit -> set to 500 seconds, CloudFlare was also disabled as their connection limit was much lower set to 100 seconds. 

We also realized the script still runs in the background even with timeout and to check mod_crisp table for the # of records. It should be equal to tblclients and tblclients added -- minus a few as those may be imported.

If all the imports work successfully the mod_crisp table would be empty. 

I will monitor the ensure everything is imported in the morning and report back if there are any issues, thank you kindly.
