### ISSUE TITLE
PHP 8.1 / ionCube 12 Support

### ISSUE THREAD

**Issue by macaws** [lennmedia/crisp-whmcs#4]
Currently, the addon does not work when running WHMCS on PHP 8.1/ionCube 12. The following error is produced

`Whoops\Exception\ErrorException: The file /.../modules/addons/crisp/crisp.php encoded as type [1/71] cannot be decoded by this version of the ionCube Loader.
in Unknown:0
Stack trace:
#0 /.../vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError()
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}`

**Comment by lennarttd** [comment]
Hi macaws,

We are aware of this issue and expect to release a PHP 8.1 compatible version within 1-2 weeks.

**Comment by joshcannotcode** [comment]
Hi @lennarttd, any update on this?

**Comment by lennarttd** [comment]
Hi Josh. We expect to release an updated version including new functionality and PHP 8.1 support by end of next month. Thanks for your patience!

**Comment by lennarttd** [comment]
Hi guys. Just wanted to give you a heads up that the PHP 8.1 support has just been released with v2.12 🚀

**Comment by joshcannotcode** [comment]
Hey! Thanks for this - although this error seems to be showing in the Addon Modules page of WHMCS after replacing it
![image](https://github.com/lennmedia/crisp-whmcs/assets/19347018/081a6b2f-6787-4f16-a296-e0fed0ae3f66)

**Comment by lennarttd** [comment]
Hi Josh. Are you running ionCube v12? Please feel free to hop on to our chat so we can run some diagnostics.

**Comment by notjoshmiles** [comment]
Yup, “ionCube PHP Loader v12.0.5” according to phpinfo… where can I hop on a chat?

**Comment by lennarttd** [comment]
www.lennmedia.nl - I will fetch your Crisp chat from there 😉

**Comment by lennarttd** [comment]
Updated downloads for v2.12 including encodings for both PHP 7.x and PHP 8.x versions.
