### ISSUE TITLE
+ in front of email

### ISSUE THREAD

**Issue by lennarttd** [lennmedia/crisp-whmcs#6]
@tope-pd I also notice an issue when a client is not logged in to WHMCS and initiate a chat and Crisp ask for email address. It will create another client in CRM with a `+` in front of the email. Hence, creating a duplicate entry in CRM that cannot be merged automatically. 
See screenshot:
![CleanShot 2023-07-02 at 14 36 38](https://github.com/lennmedia/crisp-whmcs/assets/59085206/77fd2586-f813-4e8f-bea5-1b33c9dd1580)
![CleanShot 2023-07-02 at 14 36 50](https://github.com/lennmedia/crisp-whmcs/assets/59085206/7e765a37-aa41-4e75-a326-43d820e610d9)

_Originally posted by @webhostsg in https://github.com/lennmedia/crisp-whmcs/issues/5#issuecomment-1616409706_

**Comment by lennarttd** [comment]
I have an explanation for the + sign. Could you maybe check in the Addon Settings of WHMCS if both the checkboxes for Session Continuity are ticked?
To use Identity Verification we had to implement a hotfix which adds a + to the clients' email address upon login and removes this after login. This might only work if the Session Continuity features are on.

<img width="854" src="https://github.com/lennmedia/crisp-whmcs/assets/22932993/92f716d6-98c8-4054-9b97-03e1915144f8">

**Comment by tope-pd** [comment]
Hi @lennarttd, both checkboxes are ticked for me.

**Comment by lennarttd** [comment]
Ok, it might be the hotfix is not necessary anymore. We will reproduce the issue and let you know when it's fixed!

**Comment by tope-pd** [comment]
Thank you so much

**Comment by webhostsg** [comment]
Both checkboxes are ticked on mine too

![CleanShot 2023-07-04 at 21 11 02](https://github.com/lennmedia/crisp-whmcs/assets/59085206/1552ec15-ed5f-470a-998b-9630b733f25f)

**Comment by lennarttd** [comment]
Fixed in v2.13
