### ISSUE TITLE
Login as client not working. 

### ISSUE THREAD

**Issue by webhostsg** [lennmedia/crisp-whmcs#7]
Everything else worked, but when I click on `Login as client` it shows this:
![CleanShot 2023-09-27 at 16 59 48](https://github.com/lennmedia/crisp-whmcs/assets/59085206/09fb8913-c55a-48ef-98ed-068fc868c2e4)

**Comment by lennarttd** [comment]
Hi @webhostsg 
We've had some problems communicating with the Crisp API this morning due to an IPv6 connection issue. A hotfix just got deployed, so the plugin should work as normal again. Thank you for your patience!

**Comment by webhostsg** [comment]
Ok,
Yes, working now. Thank you.
