### ISSUE TITLE
Incompatible with PHP 7.4

### ISSUE THREAD

**Issue by julienmru** [lennmedia/crisp-whmcs#8]
Dear team,

We have some addons which are not yet compatible with PHP 8.1 and it looks like the latest version is not compatible with PHP 7.4 since we are having an error "cannot be decoded by this version of the ionCube Loader" about the files.

Any chance you can ship a version compatible with PHP 7.4 as it's still being supported by WHMCS?

Thanks.

**Comment by lennarttd** [comment]
Hi Julien,

Are you making use of the PHP 7.4 version of our module? For compatibility we have 2 versions published, one for PHP 8.x with ionCube Loader 12, one for PHP 7.x with ionCube Loader 10. These also match with the [System Requirements of WHMCS](https://docs.whmcs.com/System_Requirements).

Does the PHP 7.x version work for you? https://github.com/lennmedia/crisp-whmcs/releases/tag/v2.15

**Comment by julienmru** [comment]
It works, I just download the code from the repository (`git clone`) instead of the release.
Thanks :)
